version: "3"
services:
  mysql_8:
    container_name: mysql_svc
    image: mysql/mysql-server:8.0
    networks:
      - svc_net
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ROOT_HOST=%
    volumes:
      - "./service_storage/mysql:/var/lib/mysql"

  mysql_5:
     container_name: mysql_svc5
     image: mysql/mysql-server:5.7
     networks:
       - svc_net
     ports:
       - "33065:3306"
     environment:
       - MYSQL_ROOT_PASSWORD=
       - MYSQL_ROOT_HOST=%
     volumes:
       - "./service_storage/mysql5:/var/lib/mysql"

  postgres_13:
    container_name: postgres_svc_final
    image: postgres:13.4-alpine
    shm_size: 1g
    ports:
      - "5432:5432"
    networks:
      - svc_net
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
    volumes:
      - "./service_storage/postgres:/var/lib/postgresql/data"

  redis_latest:
     container_name: redis_svc
     image: redis:latest
     ports:
       - '6379:6379'
     command: redis-server --requirepass password
     volumes:
       - './service_storage/redis:/data'
     networks:
       - svc_net

  minio_latest:
     container_name: minio_svc
     image: minio/minio:latest
     ports:
       - "9000:9000"
       - "9001:9001"
     volumes:
       - "./service_storage/minio:/data"
     networks:
       - svc_net
     environment:
       - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
       - MINIO_ROOT_PASSWORD=
     command: server /data --console-address ":9001"

  portainer:
    container_name: portainer_svc
    image: portainer/portainer:latest
    ports:
      - "10000:8000"
      - "10001:9000"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./service_storage/portainer:/data portainer/portainer-ce"

  phpmyadmin:
    container_name: mysqladmin_svc
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ROOT_HOST=%
      - PMA_HOST=mysql_svc
      - PMA_PORT=3306
    ports:
      - 33061:80

networks:
  svc_net:
    driver: bridge
